/*
Navicat MySQL Data Transfer

Source Server         : web
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : bakeacademy

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2023-06-05 13:35:22
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for `bookmark`
-- ----------------------------
DROP TABLE IF EXISTS `bookmark`;
CREATE TABLE `bookmark` (
  `id` int(11) NOT NULL,
  `id_user` int(11) DEFAULT NULL,
  `id_resep` int(11) DEFAULT NULL,
  `foto` text DEFAULT NULL,
  `tanggal` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user1` (`id_user`),
  KEY `resep1` (`id_resep`),
  CONSTRAINT `resep1` FOREIGN KEY (`id_resep`) REFERENCES `resep` (`id`),
  CONSTRAINT `user1` FOREIGN KEY (`id_user`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ----------------------------
-- Records of bookmark
-- ----------------------------

-- ----------------------------
-- Table structure for `resep`
-- ----------------------------
DROP TABLE IF EXISTS `resep`;
CREATE TABLE `resep` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) DEFAULT '',
  `deskripsi` text DEFAULT NULL,
  `bahan` text DEFAULT NULL,
  `langkah` text DEFAULT NULL,
  `nutrisi` text DEFAULT NULL,
  `link` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ----------------------------
-- Records of resep
-- ----------------------------
INSERT INTO `resep` VALUES ('1', 'Bagel', 'Roti bagel adalah jenis roti berbentuk cincin dengan permukaan yang kenyal dan renyah di luar namun lembut di dalam. Roti ini memiliki rasa yang sedikit asin dan umumnya disajikan dengan berbagai macam topping seperti biji wijen, garam kasar, atau bawang putih cincang.', '20 grams of wheat flour,\r\n1.5 teaspoons instant yeast,\r\n2 teaspoons of granulated sugar,\r\n250 ml of warm water,\r\n1 tablespoon of vegetable oil,\r\n1 egg', 'Dalam mangkuk besar, campurkan tepung terigu, ragi instan, gula, dan garam. Aduk rata. , Oleskan minyak sayur ke dalam mangkuk, letakkan adonan roti di dalamnya, dan gulingkan adonan agar terlapisi minyak. Tutup mangkuk dengan kain bersih dan biarkan adonan mengembang selama sekitar 1 jam hingga dua kali lipat ukuran aslinya. , Setelah adonan mengembang, kembali letakkan adonan di permukaan yang telah ditaburi tepung. Bagi adonan menjadi beberapa bagian sesuai dengan ukuran yang diinginkan. , Bentuk masing-masing bagian adonan menjadi bola dan buat lubang di tengahnya menggunakan jari. Bentuklah adonan menjadi cincin dengan memperlebar lubang dan meratakan adonan.\r\n , Panaskan air dalam panci besar. Setelah mendidih, tambahkan gula pasir secukupnya.\r\n , Rebus bagel dalam air mendidih selama sekitar 1-2 menit per sisi. Angkat dengan menggunakan sendok berlubang dan tiriskan.\r\n , Tempatkan bagel yang sudah direbus di atas loyang yang telah dialasi dengan kertas roti atau dilapisi dengan tepung terigu.\r\n , Tambahkan topping sesuai selera pada bagel yang sudah direbus.\r\n , Panggang dalam oven yang telah dipanaskan pada suhu 200°C selama sekitar 20-25 menit atau hingga bagel berwarna kecokelatan.\r\n , Setelah matang, angkat dari oven dan biarkan bagel dingin sejenak sebelum disajikan.\r\n\r\n\r\n', 'gizi/bagel.json', 'https://www.youtube.com/watch?v=xELS2JTn8vk', '2023-06-04 01:06:13', '2023-06-04 01:06:13');
INSERT INTO `resep` VALUES ('2', 'Baguette', 'Roti baguette adalah roti panjang dan ramping yang berasal dari Prancis. Roti ini memiliki kulit yang renyah dan kering, sementara bagian dalamnya lembut dan berongga. Baguette memiliki rasa yang sedikit asin dengan sentuhan rasa gandum yang khas. Baguette sering disajikan sebagai roti utama dalam hidangan seperti sandwich, bruschetta, atau crostini. Roti ini juga digunakan sebagai pendamping dalam hidangan seperti sup atau hidangan pembuka. Baguette segar yang baru dipanggang memiliki aroma yang menggoda dan memberikan sensasi renyah saat digigit.\r\n\r\n', '500 grams of bread flour,\r\n10 grams of instant yeast,\r\n10 grams of salt,\r\n350 milliliters of water', 'Dalam mangkuk besar, campurkan tepung terigu, ragi instan, dan garam. Aduk rata. , Tuangkan air hangat sedikit demi sedikit ke dalam campuran tepung sambil terus diaduk dengan sendok kayu atau spatula. Aduk hingga adonan tercampur dengan baik dan mulai membentuk adonan. , Pindahkan adonan ke permukaan yang telah ditaburi tepung dan uleni selama sekitar 10 menit sampai elastis dan halus. , Letakkan adonan dalam mangkuk yang telah diolesi minyak zaitun, tutup mangkuk dengan kain bersih, dan biarkan adonan mengembang selama sekitar 1-2 jam hingga dua kali lipat ukuran aslinya.\r\n , Setelah adonan mengembang, kembali letakkan adonan di permukaan yang telah ditaburi tepung. Tekan perlahan dan ratakan adonan menjadi persegi panjang.\r\n , Lipat adonan seperti amplop dari bagian atas dan bawahnya, kemudian gulung adonan menjadi bentuk tabung panjang.\r\n , Letakkan roti baguette yang sudah digulung di atas loyang yang telah dialasi dengan kertas roti atau dilapisi dengan tepung terigu. Tutup lagi dengan kain bersih dan biarkan roti mengembang selama sekitar 30-60 menit.\r\n , Panaskan oven pada suhu 220°C.\r\n , Sebelum memasukkan roti ke dalam oven, buat sayatan miring pada permukaan roti dengan pisau tajam. Hal ini akan membantu roti mengembang dengan baik.\r\n , Panggang roti dalam oven yang telah dipanaskan selama sekitar 20-25 menit atau hingga roti berwarna kecokelatan dan berkulit renyah. , Setelah matang, angkat roti baguette dari oven dan biarkan dingin sejenak sebelum disajikan.\r\n\r\n\r\n', 'gizi/baguette.json', 'https://www.youtube.com/watch?v=m08i8oXpFB0', '2023-06-04 01:14:34', '2023-06-04 01:14:34');
INSERT INTO `resep` VALUES ('3', 'Biscuits', 'Roti biscuits adalah roti kecil, ringan, dan berlapis yang biasanya disajikan sebagai sarapan atau camilan. Roti ini berasal dari Amerika Serikat dan memiliki tekstur yang renyah di luar, namun lembut dan berongga di dalam.\r\n\r\n', '2 cups all-purpose flour,\r\n1 tablespoon baking powder,\r\n1 teaspoon salt,\r\n6 tablespoons cold unsalted butter, cut into small cubes,\r\n3/4 cup milk', 'Panaskan oven hingga suhu 220°C dan siapkan loyang dengan menggunakan kertas roti atau diolesi mentega.\r\n , Dalam mangkuk besar, campurkan tepung terigu, baking powder, dan garam. Aduk rata.\r\n , Tambahkan mentega dingin ke dalam campuran tepung. Gunakan jari atau pastry cutter untuk memadatkan mentega ke dalam tepung hingga teksturnya menjadi seperti remah-remah halus.\r\n , Tuangkan susu ke dalam campuran tepung dan mentega. Aduk dengan sendok kayu atau spatula hanya sampai adonan tercampur dengan baik. Pastikan tidak mengaduk terlalu lama agar roti tidak menjadi keras.\r\n , Pindahkan adonan ke permukaan yang ditaburi tepung dan ratakan menjadi sekitar setebal 2,5 cm.\r\n , Gunakan cutter roti berbentuk bulat atau gelas untuk memotong adonan menjadi bentuk biscuits. Tekan cutter roti dengan perlahan tanpa memutar agar biscuits tetap naik saat dipanggang.\r\n , Letakkan biscuits yang sudah dipotong di atas loyang yang telah disiapkan.\r\n , Panggang biscuits dalam oven selama sekitar 12-15 menit, atau hingga bagian atasnya berwarna keemasan.\r\n , Setelah matang, angkat biscuits dari oven dan biarkan dingin sejenak sebelum disajikan.\r\n', 'gizi/biscuits.json', 'https://www.youtube.com/watch?v=u9rjIag6W-s', '2023-06-04 01:18:57', '2023-06-04 01:18:57');
INSERT INTO `resep` VALUES ('4', 'Croissants', 'Croissant adalah roti lembut dan berlapis yang berasal dari Prancis. Roti ini memiliki bentuk melengkung yang khas dan lapisan-lapisan tipis yang terbentuk saat proses pembuatannya. Croissant memiliki rasa buttery yang kaya dan tekstur yang renyah di luar, sementara bagian dalamnya lembut dan berongga.\r\n\r\n', '3.5 cups all-purpose flour,\r\n1/4 cup granulated sugar,\r\n2.5 teaspoons instant yeast,\r\n1 teaspoon salt,\r\n1.25 cups warm milk,\r\n2.5 tablespoons unsalted butter,\r\n226 grams cold unsalted butter', 'Dalam mangkuk besar, campurkan tepung terigu, gula pasir, ragi instan, dan garam. Aduk rata.\r\n , Tambahkan susu hangat sedikit demi sedikit ke dalam campuran tepung sambil diaduk dengan sendok kayu atau spatula hingga adonan tercampur rata.\r\n , Setelah adonan tercampur, uleni adonan dengan tangan atau menggunakan mixer dengan hook selama sekitar 10-15 menit hingga adonan elastis dan halus.\r\n , Letakkan adonan dalam mangkuk, tutup dengan plastik wrap, dan biarkan adonan mengembang selama sekitar 1-2 jam hingga adonan mengembang dua kali lipat ukuran aslinya.\r\n , Sementara adonan mengembang, siapkan mentega dingin. Letakkan mentega dingin di atas lembaran kertas roti dan pipihkan mentega dengan menggunakan rolling pin hingga membentuk persegi panjang dengan ketebalan sekitar 1 cm.\r\n , Dinginkan mentega dalam lembaran kertas roti di dalam lemari es selama sekitar 10-15 menit hingga mentega kembali dingin.\r\n , Setelah adonan roti mengembang, letakkan adonan di atas permukaan yang ditaburi tepung terigu. Gulingkan adonan hingga membentuk persegi panjang dengan ketebalan sekitar 1 cm.\r\n , Letakkan lembaran mentega dingin di tengah adonan dan lipat adonan menjadi tiga bagian seperti amplop, sehingga mentega tertutup rapat di dalam adonan.\r\n , Gulingkan adonan hingga membentuk persegi panjang dengan ketebalan sekitar 1 cm.\r\n , Lipat adonan menjadi tiga bagian seperti amplop lagi. Ini adalah satu lapisan.\r\n , Bungkus adonan dengan plastik wrap dan dinginkan dalam lemari es selama sekitar 20-30 menit.\r\n , Ulangi langkah 8 hingga 11 sebanyak dua kali lagi untuk membuat total tiga lapisan pada adonan.\r\n , Setelah adonan siap, gulingkan adonan hingga ketebalannya sekitar 5-6 mm.\r\n , Potong adonan menjadi segitiga dan gulung setiap segitiga dari ujung lebar ke ujung tajam untuk membentuk bentuk croissant.\r\n , Letakkan croissant yang sudah digulung di atas loyang yang telah dialasi dengan kertas roti. Biarkan croissant mengembang selama sekitar 1 jam hingga ukurannya membesar.\r\n , Sebelum memanggang, panaskan oven pada suhu 200°C.\r\n , Setelah croissant mengembang, oleskan permukaannya dengan kuning telur yang telah dikocok lepas.\r\n , Panggang croissant dalam oven\r\n\r\n\r\n\r\n', 'gizi/croissant.json', 'https://www.youtube.com/watch?v=K689erbK3XI', '2023-06-04 03:01:07', '2023-06-04 03:01:07');
INSERT INTO `resep` VALUES ('5', 'English Muffin', 'Roti English muffin adalah roti bundar, pipih, dan berlubang di tengahnya yang berasal dari Inggris. Roti ini memiliki tekstur yang lembut di dalam, tetapi memiliki lapisan luar yang renyah. Roti English muffin sering digunakan untuk membuat sandwich, khususnya untuk sarapan.', '3.5 cups all-purpose flour,\r\n1 tablespoon granulated sugar,\r\n1 teaspoon salt,\r\n2.25 teaspoons instant yeast,\r\n1.25 cups warm milk,\r\n2 tablespoons unsalted butter', 'Panaskan oven pada suhu 180°C (350°F). Siapkan loyang muffin dengan menggunakan liner kertas atau mengolesinya dengan mentega atau minyak.\r\n , Dalam mangkuk besar, campurkan tepung terigu, gula pasir, baking powder, dan garam. Aduk rata.\r\n , Dalam mangkuk terpisah, campurkan susu, minyak sayur, telur, dan ekstrak vanila. Kocok hingga tercampur rata.\r\n , Tuangkan campuran basah ke dalam campuran kering. Aduk dengan spatula hingga semua bahan tercampur rata. Jika ingin menambahkan isian seperti potongan buah atau cokelat chip, tambahkan pada tahap ini dan aduk rata.\r\n , Tuangkan adonan ke dalam mangkuk muffin, mengisi setiap mangkuk sekitar 2/3 penuh.\r\n , Panggang dalam oven yang sudah dipanaskan selama sekitar 18-20 menit, atau hingga roti muffin berwarna keemasan dan saat tusuk gigi dimasukkan ke tengah roti muffin, keluar bersih.\r\n , Setelah matang, angkat roti muffin dari loyang dan biarkan dingin sejenak di atas rak pendingin.\r\n , Sajikan roti muffin hangat atau dingin sebagai camilan atau sarapan yang lezat.\r\n', 'gizi/english-muffin.json', 'https://www.youtube.com/watch?v=CEvr9Jgxe1g', '2023-06-04 01:31:43', '2023-06-04 01:31:43');
INSERT INTO `resep` VALUES ('6', 'Focaccia', 'Roti focaccia adalah sejenis roti Italia yang memiliki tekstur empuk di bagian dalam dan kulit yang renyah di bagian luar. Roti ini memiliki aroma yang harum dan rasa yang gurih. Focaccia umumnya memiliki bentuk pipih dan lebar, mirip dengan pizza, namun lebih tebal.', '500 grams all-purpose flour,\r\n2 teaspoons instant yeast,\r\n1.5 teaspoons salt,\r\n1.5 teaspoons sugar,\r\n350 ml warm water,\r\n60 ml olive oil', 'Dalam mangkuk besar, campurkan tepung terigu, ragi instan, garam, dan gula. Aduk rata. , Tambahkan air hangat dan minyak zaitun. Uleni adonan menggunakan tangan atau mixer dengan pengaduk kait pada kecepatan rendah hingga adonan tercampur dengan baik dan membentuk bola. , Pindahkan adonan ke permukaan kerja yang ditaburi dengan sedikit tepung terigu. Uleni adonan selama sekitar 10-15 menit hingga elastis dan tidak lengket. , Tempatkan adonan dalam mangkuk yang diolesi minyak zaitun, kemudian tutup dengan kain bersih. Biarkan adonan mengembang selama sekitar 1-2 jam atau hingga ukurannya menjadi dua kali lipat. , Setelah adonan mengembang, tuangkan adonan ke dalam loyang persegi panjang yang diolesi minyak zaitun. Ratakan adonan menggunakan tangan, sehingga merata di dalam loyang. , Tutup loyang dengan kain bersih dan biarkan adonan mengembang lagi selama sekitar 30-45 menit. , Panaskan oven hingga suhu 200 derajat Celsius. , Setelah adonan mengembang kembali, buat cekungan kecil di permukaan roti menggunakan ujung jari. Olesi permukaan roti dengan minyak zaitun dan taburkan garam kasar di atasnya. Jika diinginkan, tambahkan daun rosemary segar dan bawang putih cincang halus. , Panggang roti dalam oven yang telah dipanaskan selama sekitar 20-25 menit atau hingga permukaan roti berwarna kecokelatan. , Setelah matang, angkat roti focaccia dari loyang dan dinginkan sejenak di atas rak pendingin. , Potong-potong roti focaccia menjadi persegi atau segitiga sebelum disajikan.', 'gizi/focaccia.json', 'https://www.youtube.com/watch?v=-DmVedGWAnU', '2023-06-04 20:05:32', '2023-06-04 20:05:31');
INSERT INTO `resep` VALUES ('7', 'Mantou', 'Roti mantou adalah sejenis roti tradisional Tiongkok yang terkenal karena teksturnya yang lembut, putih, dan tidak beragi. Roti ini memiliki bentuk bulat atau oval dengan permukaan yang halus. Roti mantou sering kali memiliki rasa yang sangat sederhana, sehingga cocok digunakan sebagai dasar untuk hidangan lain atau dimakan sebagai camilan.', '500 grams all-purpose flour,\r\n10 grams instant yeast,\r\n2 tablespoons sugar,\r\n250 ml warm water,\r\n1 tablespoon vegetable oil', 'Dalam mangkuk besar, campurkan tepung terigu, ragi instan, gula, dan garam (jika digunakan). Aduk rata. , Secara bertahap, tambahkan air hangat sambil mengaduk bahan kering. Aduk hingga adonan membentuk gumpalan yang kasar. , Pindahkan adonan ke permukaan kerja yang ditaburi tepung dan uleni selama sekitar 5-10 menit hingga adonan menjadi lembut dan elastis. , Letakkan adonan dalam mangkuk yang diolesi minyak dan tutup dengan kain bersih. Biarkan adonan mengembang di tempat hangat selama sekitar 1-2 jam atau hingga ukurannya menjadi dua kali lipat. , Setelah adonan mengembang, tekan adonan untuk mengeluarkan udara. Pindahkan kembali adonan ke permukaan kerja yang ditaburi tepung dan uleni sebentar untuk menghilangkan gelembung udara. , Giling adonan menjadi bentuk silinder panjang, dengan diameter sekitar 2 sentimeter. , Potong adonan menjadi potongan-potongan kecil, sekitar 3-4 sentimeter setiap potong. , Ambil setiap potongan dan pipihkan sedikit dengan telapak tangan. Opsional, Anda dapat melipat setiap potongan menjadi bentuk lipatan mantou. , Letakkan mantou di atas selembar kertas roti kecil untuk mencegah lengket. , Siapkan alat pengukus dan panaskan air hingga mendidih. Tempatkan mantou, masih di atas kertas roti, di dalam keranjang pengukus, pastikan untuk meninggalkan sedikit ruang antara setiap potongan. , Kukus mantou selama sekitar 15-20 menit, atau hingga mantou mengembang dan matang. , Setelah matang, angkat mantou dari pengukus dan biarkan sedikit dingin sebelum disajikan.', 'gizi/mantou.json', 'https://www.youtube.com/watch?v=NIERMXJtuYU', '2023-06-04 20:05:33', '2023-06-04 20:05:35');
INSERT INTO `resep` VALUES ('8', 'Naan', 'Roti naan adalah sejenis roti datar yang berasal dari masakan India. Roti ini terkenal karena teksturnya yang lembut dan kenyal, serta rasa yang kaya. Naan biasanya dibuat dengan menggunakan tepung terigu, ragi, yogurt, dan bahan-bahan lainnya.', '2 cups all-purpose flour,\r\n1 teaspoon instant yeast,\r\n1 teaspoon sugar,\r\n1/2 teaspoon salt,\r\n1/4 cup plain yogurt,\r\n1/4 cup warm milk,\r\n2 tablespoons vegetable oil,\r\n1/4 cup melted butter', 'Dalam mangkuk besar, campurkan tepung terigu, ragi instan, gula, dan garam. Aduk rata. , Tambahkan yogurt, susu hangat, dan minyak sayur ke dalam bahan kering. Aduk hingga adonan tercampur. , Pindahkan adonan ke permukaan kerja yang ditaburi tepung dan uleni selama sekitar 5-7 menit hingga adonan menjadi halus dan elastis. , Letakkan adonan dalam mangkuk yang diolesi minyak, tutup dengan kain bersih, dan biarkan adonan mengembang di tempat hangat selama sekitar 1-2 jam atau hingga ukurannya menjadi dua kali lipat. , Setelah adonan mengembang, tekan adonan untuk mengeluarkan udara. Bagi adonan menjadi 6-8 bagian yang sama. , Panaskan penggorengan datar atau tava tanpa lengket di atas api sedang-tinggi. , Ambil satu bagian adonan dan giling menjadi bentuk oval atau bulat, dengan ketebalan sekitar 1/4 inci. , Tempatkan naan yang telah digulung ke dalam penggorengan datar yang sudah dipanaskan dan masak selama sekitar 1-2 menit atau hingga muncul gelembung di permukaannya. , Balik naan dan masak selama 1-2 menit lagi hingga naan mengembang dan mendapatkan bintik-bintik cokelat keemasan. , Angkat naan dari penggorengan dan olesi dengan mentega cair. Opsional, taburi daun ketumbar atau bawang putih cincang di atasnya untuk memberikan rasa tambahan. , Ulangi proses dengan sisa bagian adonan. , Sajikan naan hangat dan nikmati dengan hidangan India favorit atau sebagai camilan sendiri.', 'gizi/naan.json', 'https://www.youtube.com/watch?v=EqCUENkCQqw', '2023-06-04 20:05:37', '2023-06-04 20:05:39');
INSERT INTO `resep` VALUES ('9', 'Pretzel', 'Roti pretzel adalah roti yang memiliki bentuk khas seperti tali yang terpilin dengan permukaan yang berwarna kecokelatan dan renyah. Roti ini berasal dari Jerman dan menjadi populer di berbagai negara.', '4 cups all-purpose flour,\r\n2 teaspoons active dry yeast,\r\n2 tablespoons brown sugar,\r\n1.5 teaspoons salt,\r\n1.5 cups warm water,\r\n2 tablespoons baking soda,\r\nCoarse salt, for topping,\r\n0.25 cup unsalted butter', 'Dalam mangkuk besar, campurkan tepung terigu, ragi instan, gula coklat, dan garam. Aduk rata. , Secara bertahap tambahkan air hangat ke dalam bahan kering sambil diaduk. Aduk hingga adonan tercampur. , Pindahkan adonan ke permukaan kerja yang ditaburi tepung dan uleni selama sekitar 5-7 menit hingga adonan menjadi halus dan elastis. , Letakkan adonan dalam mangkuk yang diolesi minyak, tutup dengan kain bersih, dan biarkan adonan mengembang di tempat hangat selama sekitar 1 jam atau hingga ukurannya menjadi dua kali lipat. , Panaskan oven hingga 450°F (230°C) dan lapisi loyang dengan kertas roti. , Tekan adonan yang telah mengembang dan bagi menjadi beberapa bagian yang sama besar, tergantung seberapa besar pretzel yang Anda inginkan. , Gulung setiap bagian adonan menjadi bentuk tali panjang, sekitar 20-22 inci. , Untuk membentuk bentuk pretzel, bentuklah tali adonan menjadi bentuk U. Silangkan ujung tali adonan dua kali, lalu tekan ujungnya pada bagian bawah lengkungan U untuk membentuk bentuk pretzel klasik. , Dalam panci besar, didihkan air. Tambahkan soda kue ke dalam air mendidih. , Masukkan perlahan masing-masing pretzel ke dalam air mendidih dan biarkan masak selama sekitar 30 detik. Angkat dengan menggunakan sendok berlubang dan letakkan di atas loyang yang telah disiapkan. Ulangi dengan pretzel yang lain. , Taburkan garam kasar di atas pretzel sebagai taburan. , Panggang pretzel dalam oven yang telah dipanaskan selama sekitar 12-15 menit atau hingga berwarna kecokelatan. , Angkat pretzel dari oven dan oleskan dengan mentega cair. , Dinginkan pretzel sejenak sebelum disajikan.', 'gizi/pretzel.json', 'https://www.youtube.com/watch?v=WMx9ynviC3o', '2023-06-04 20:05:45', '2023-06-04 20:05:44');
INSERT INTO `resep` VALUES ('10', 'Sourdough', 'Roti sourdough adalah roti yang dibuat dengan menggunakan starter atau kultur asam sebagai agen pengembang alami. Starter ini terdiri dari campuran tepung dan air yang difermentasi untuk menghasilkan bakteri asam dan ragi alami. Proses fermentasi ini memberikan karakteristik unik pada roti sourdough, termasuk rasa asam yang khas, tekstur yang lembut, dan kulit yang renyah.', '400 grams bread flour,\r\n300 grams sourdough starter,\r\n300 milliliters water,\r\n8 grams salt', 'Siapkan starter atau kultur asam sebelumnya. Pastikan starter Anda aktif dan telah diberi makan dalam 4-6 jam sebelum digunakan. , Campurkan 100 gram starter dengan 100 gram tepung terigu dan 100 ml air. Aduk rata, tutup dengan kain bersih, dan biarkan selama 4-6 jam pada suhu ruangan hangat hingga adonan mengembang dan berbusa. Ini disebut sebagai \"levain\" atau \"pre-ferment\". , Simpan sisa starter yang tidak digunakan di dalam wadah kedap udara dan simpan di lemari es untuk digunakan di lain waktu. , Dalam mangkuk besar, campurkan tepung terigu segitiga biru atau tepung roti dengan tepung terigu protein tinggi. Aduk rata. , Tambahkan levain yang telah dikembangkan ke dalam mangkuk dengan tepung. , Tambahkan air sedikit-sedikit sambil diaduk hingga adonan tercampur. , Diamkan adonan selama sekitar 30 menit untuk proses autolysis. Ini akan membantu gluten terbentuk. , Setelah 30 menit, tambahkan garam ke dalam adonan. Campurkan garam dengan sedikit air sebelum ditambahkan ke adonan untuk memudahkan distribusinya. , Uleni adonan dengan tangan atau menggunakan mixer dengan kecepatan rendah hingga adonan menjadi elastis dan mulai terlepas dari sisi mangkuk. , Letakkan adonan di dalam mangkuk yang telah diolesi minyak. Tutup dengan kain bersih dan biarkan mengembang selama 3-4 jam pada suhu ruangan hangat, atau hingga adonan mengembang dua kali lipat ukurannya. , Setelah fermentasi selesai, preheat oven hingga suhu 230°C. , Letakkan adonan di atas permukaan yang ditaburi tepung atau batu peka panas. , Potong permukaan adonan dengan pisau tajam sesuai dengan pola yang diinginkan. , Panggang roti dalam oven yang telah dipanaskan selama sekitar 30-40 menit, atau hingga bagian luar roti berwarna kecokelatan dan berkulit keras. , Setelah matang, dinginkan roti di atas rak sebelum dipotong dan disajikan.', 'gizi/sourdough.json', 'https://www.youtube.com/watch?v=4r8irdLuUtc', '2023-06-04 20:05:46', '2023-06-04 20:05:48');

-- ----------------------------
-- Table structure for `users`
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT '',
  `nama` varchar(255) DEFAULT NULL,
  `password` text DEFAULT NULL,
  `alergi` varchar(255) DEFAULT NULL,
  `foto` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('14', 'agus', 'agus@gmail.com', 'agus', '$2b$10$g39OwbUWUgmBttdMAzjGl.g4tBGVzczrWDQHReP5GqC4Yn7HNiYoC', 'Keju', null);
